# .github/workflows/main.yml
name: Project Docs

on: [push]

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate docs
        run: |
          mkdir -p docs/generated
          if command -v tree &> /dev/null; then
            tree -I 'node_modules|.git|.cache' -a --noreport > docs/generated/00_tree.txt
          else
            find . -type d ! -path './node_modules*' ! -path './.git*' ! -path './.cache*' \
              | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/" \
              > docs/generated/00_tree.txt
          fi

          find "$(pwd)" -type f ! -path "*/node_modules/*" ! -path "*/.git/*" ! -path "*/.cache/*" \
            | sed 's|/home/runner/workspace/||' \
            > docs/generated/01_flat_dir.txt

          (jq -r '.dependencies' package.json || \
           grep '"dependencies"' package.json | awk -F: '{print $2}') \
            > docs/generated/dependencies.txt 2>/dev/null

          [[ -f package-lock.json ]] && echo "package-lock.json exists" >> docs/generated/dependencies.txt
          [[ -f yarn.lock ]] && echo "yarn.lock exists" >> docs/generated/dependencies.txt

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/generated/*
          git diff --quiet --exit-code docs/generated/ || git commit -m "chore: update docs"
      - name: Push changes
        if: always()
        run: |
          git push
